# Generated by Django 4.2.6 on 2023-11-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ezbertakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=15)),
                ('ad', models.CharField(max_length=15)),
                ('soyad', models.CharField(max_length=15)),
                ('sayfa', models.CharField(max_length=15)),
            ],
        ),
    ]
