# Generated by Django 4.2.6 on 2023-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='okumatakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=15)),
                ('ad', models.CharField(max_length=15)),
                ('soyad', models.CharField(max_length=15)),
                ('okuma', models.CharField(default='VarsayilanDeger', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ezbertakip',
        ),
    ]
