# Generated by Django 4.2.6 on 2023-11-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0002_okumatakip_delete_ezbertakip'),
    ]

    operations = [
        migrations.AddField(
            model_name='okumatakip',
            name='aktiflik',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='okumatakip',
            name='kayitTarihi',
            field=models.DateField(null=True),
        ),
    ]
