# Generated by Django 4.2.6 on 2023-11-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0003_okumatakip_aktiflik_okumatakip_kayittarihi'),
    ]

    operations = [
    ]
