# Generated by Django 4.2.6 on 2023-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0004_auto_20231126_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='detay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitapAdi', models.CharField(max_length=20)),
                ('kitapAldigiTarih', models.DateField(auto_now_add=True)),
                ('toplamsayfa', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='okumatakip',
            name='okuma',
        ),
        migrations.AddField(
            model_name='okumatakip',
            name='okumasayfa',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
