# Generated by Django 4.2.6 on 2023-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0005_detay_remove_okumatakip_okuma_okumatakip_okumasayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='okumadetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitapAdi', models.CharField(max_length=20)),
                ('kitapAldigiTarih', models.DateField(null=True)),
                ('toplamsayfa', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='detay',
        ),
    ]
