# Generated by Django 4.2.6 on 2023-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okumatakip', '0006_okumadetay_delete_detay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okumatakip',
            name='okumasayfa',
            field=models.IntegerField(default=0),
        ),
    ]
