# Generated by Django 4.2.6 on 2023-12-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezbertakip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezbertakip',
            name='ezber',
            field=models.CharField(max_length=25),
        ),
    ]
