# Generated by Django 4.2.6 on 2024-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezbertakip', '0002_alter_ezbertakip_ezber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ezberdetay',
            name='toplamezber',
        ),
        migrations.RemoveField(
            model_name='ezbertakip',
            name='ezber',
        ),
        migrations.AddField(
            model_name='ezberdetay',
            name='ezberSayisi',
            field=models.IntegerField(null=True),
        ),
    ]
