# Generated by Django 4.2.6 on 2024-01-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezbertakip', '0003_remove_ezberdetay_toplamezber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezberdetay',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to='ezbertakip.ezbertakip'),
        ),
    ]
