# Generated by Django 4.2.6 on 2024-01-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezbertakip', '0004_ezberdetay_kullanici'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ezberdetay',
            old_name='ezbereBasladiğiTarih',
            new_name='ezbereBasladigiTarih',
        ),
    ]
